spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Walletwise
  data:
    mongodb:
      # uri: mongodb+srv://Muhammad-Saud:19811982@cluster0.cms0v4y.mongodb.net/walletwise?appName=Cluster0
      uri: ${MONGODB_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration: 10 # in hours

groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    model: "llama-3.3-70b-versatile"
    key: ${GROQ_API_KEY}
